# Generated by Django 6.0.6 on 2026-06-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
    ]
