# Generated by Django 6.0.6 on 2026-06-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='cloudinary_storage.storage.MediaCloudStorage', upload_to='post_images/'),
        ),
    ]
